### ISSUE TITLE
Exception: COM target does not implement IDispatch 

### ISSUE THREAD

**Issue by MilkyWayJoe** [Myslik/csharp-ember-handlebars#1]
Trying out the library with a web project (Web API project). I have set a directory structure with a folder called templates where I keep my `.handlebars` files, and the bundle config is set as follows:

```
bundles.Add(new Bundle("~/bundles/templates", 
            new EmberHandlebarsBundleTransform()).Include(
            "~/scripts/app/templates/*.handlebars"));
```

In my custom transform class, I iterate through the templates and register them with the `TemplateBuilder` instance, but it throws the exception `COM target does not implement IDispatch` when I call `builder.Register(templateName, template);`. 

The console project works fine and outputs the precompiled template as expected.

Here's my custom transform class. Note that I've replaced the template coming from the handlebars file with a "plain text" just be sure it wasn't an issue with the template itself as the original template is rather complex.

```
public class EmberHandlebarsBundleTransform : IBundleTransform
{
    Ember.Handlebars.TemplateBuilder builder = null;

    public EmberHandlebarsBundleTransform()
    {
        builder = new Ember.Handlebars.TemplateBuilder();
    }

    public void Process(BundleContext context, BundleResponse response)
    {
        var usTextInfo = new CultureInfo("en-US", false).TextInfo;

        foreach (var assetFile in response.Files)
        {
            //var template = File.ReadAllText(assetFile.FullName)
            //                   .Replace("\r", string.Empty)
            //                   .Replace("\n", string.Empty)
            //                   .Replace("\t", string.Empty);
            var template = "<div>Pain Text</div>";
            var templateName = Path.GetFileNameWithoutExtension(assetFile.FullName);
            templateName = usTextInfo.ToTitleCase(templateName).Replace("_", string.Empty);
            builder.Register(templateName, template);
        }

        response.Content = builder.ToString();
        response.ContentType = "text/javascript";
        response.Cacheability = HttpCacheability.Public;
    }
}
```

**Stack:**

`at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args)
   at Moravia.Utils.ParsedScript.CallMethod(String methodName, Object[] arguments) in c:\Users\tsantos\Documents\GitHub\csharp-ember-handlebars\Ember.Handlebars\ScriptEngine.cs:line 536
   at Ember.Handlebars.Compiler.Precompile(String template) in c:\Users\tsantos\Documents\GitHub\csharp-ember-handlebars\Ember.Handlebars\Handlebars.cs:line 38
   at Ember.Handlebars.TemplateBuilder.Register(String templateName, String templateBody) in c:\Users\tsantos\Documents\GitHub\csharp-ember-handlebars\Ember.Handlebars\Handlebars.cs:line 55
   at Ember.Handlebars.ExampleWebAPI.EmberHandlebarsBundleTransform.Process(BundleContext context, BundleResponse response) in c:\Users\tsantos\Documents\GitHub\csharp-ember-handlebars\Ember.Handlebars.ExampleWebAPI\App_Start\HandlebarsBundleTransform.cs:line 31
   at System.Web.Optimization.Bundle.ApplyTransforms(BundleContext context, String bundleContent, IEnumerable 1 bundleFiles)
   at System.Web.Optimization.Bundle.GenerateBundleResponse(BundleContext context)
   at System.Web.Optimization.Bundle.GetBundleResponse(BundleContext context)
   at System.Web.Optimization.BundleResolver.GetBundleContents(String virtualPath)
   at System.Web.Optimization.AssetManager.EliminateDuplicatesAndResolveUrls(IEnumerable 1 paths)
   at System.Web.Optimization.AssetManager.DeterminePathsToRender(IEnumerable 1 assets)
   at System.Web.Optimization.AssetManager.RenderScripts(IEnumerable 1 assets)
   at System.Web.Optimization.AssetManager.RenderExplicit(Boolean forStyles, String[] paths)
   at System.Web.Optimization.Scripts.Render(String[] paths)
   at ASP._Page_Views_Shared__Layout_cshtml.Execute() in c:\Users\tsantos\Documents\GitHub\csharp-ember-handlebars\Ember.Handlebars.ExampleWebAPI\Views\Shared\_Layout.cshtml:line 14
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.WebPages.WebPageBase.<>c__DisplayClass7.<RenderPageCore>b__6(TextWriter writer)
   at System.Web.WebPages.HelperResult.WriteTo(TextWriter writer)
   at System.Web.WebPages.WebPageBase.Write(HelperResult result)
   at System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action 1 body)
   at System.Web.WebPages.WebPageBase.PopContext()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<InvokeActionResultWithFilters>b__17()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func 1 continuation)`

**Comment by Myslik** [comment]
How are you rendering this bundle into the `_Layout.cshtml`?

Something like this?

``` html
<script type="text/javascript" src="@Url.Content("~/bundles/templates")"></script>
```

Since this is not the `ScriptBundle`, you probably cannot use the `@Scripts.Render("~/bundles/templates")`.

**Comment by MilkyWayJoe** [comment]
This is a `Bundle`, not `ScriptBundle`, but should render normally with `@Scripts.Render`. I've done something very similar to it before using Jurassic based on this gist https://gist.github.com/3214433 
I have not tried with the `script` tag and `@Url.Content`. Will try it today.

**Comment by Myslik** [comment]
To be honest I am not sure how `@Scripts.Render` works inside, but seems to me that it causes this Exception.

If you are interested I have added an example `IBundleTransform` into README.md.

**Comment by MilkyWayJoe** [comment]
Thanks.
Looking at your code I figured out what's wrong with mine. 
I have declared `builder` as a class member, when it should be declared as method variable inside `Process`. I guess due to multi-threading and/or unmanaged code it behaves differently from what I originally anticipated. 

My bundle transform class now looks like this and works beautifully:

```
namespace Ember.Handlebars.ExampleWebAPI
{
    public class EmberHandlebarsBundleTransform : IBundleTransform
    {
        public void Process(BundleContext context, BundleResponse response)
        {
            // must be declared within the method scope and not as a class member
            Ember.Handlebars.TemplateBuilder builder = new Ember.Handlebars.TemplateBuilder();
            var usTextInfo = new CultureInfo("en-US", false).TextInfo;

            foreach (var assetFile in response.Files)
            {
                var template = File.ReadAllText(assetFile.FullName)
                                   .Replace("\r", string.Empty)
                                   .Replace("\n", string.Empty)
                                   .Replace("\t", string.Empty);

                var templateName = Path.GetFileNameWithoutExtension(assetFile.FullName);
                templateName = usTextInfo.ToTitleCase(templateName).Replace("_", string.Empty);
                builder.Register(templateName, template);
            }

            response.Content = builder.ToString();
            response.ContentType = "text/javascript";
            response.Cacheability = HttpCacheability.Public;
        }
    }
}
```

My bundles are the same as before: 

```
        bundles.Add(new Bundle("~/bundles/base", new JsMinify()).Include(
                    "~/scripts/vendor/jquery-1.8.3.js",
                    "~/scripts/vendor/handlebars.js",
                    "~/scripts/vendor/ember.js"));

        bundles.Add(new Bundle("~/bundles/modernizr", new JsMinify()).Include(
                    "~/scripts/modernizr-*"));

        bundles.Add(new Bundle("~/bundles/templates", new EmberHandlebarsBundleTransform())
                    .Include("~/scripts/app/templates/*.handlebars"));

        bundles.Add(new Bundle("~/bundles/app", new JsMinify()).Include(
                    "~/scripts/app/models/*.js",
                    "~/scripts/app/views/*.js",
                    "~/scripts/app/controllers/*.js",
                    "~/scripts/app/App.js"));
```

And at the `_Layout.cshtml` I'm rendering with `@Scripts.Render` as follows:

```
@RenderBody()

@Scripts.Render("~/bundles/base")
@Scripts.Render("~/bundles/templates")
@Scripts.Render("~/bundles/app")
```

Works perfectly now
